export const FETCH_ALL_AIRPORT = "FETCH_ALL_AIRPORT";
export const CREATE_AIRPORT = "CREATE_AIRPORT";
export const DELETE_AIRPORT = "DELETE_AIRPORT";
export const UPDATE_AIRPORT = "UPDATE_AIRPORT";
export const SEARCH_AIRPORT = "SEARCH_AIRPORT";
