export const FETCH_ALL_FLIGHT = "FETCH_ALL_FLIGHT";
export const CREATE_FLIGHT = "CREATE_FLIGHT";
export const DELETE_FLIGHT = "DELETE_FLIGHT";
export const UPDATE_FLIGHT = "UPDATE_FLIGHT";
export const SEARCH_FLIGHT = "SEARCH_FLIGHT";
export const TOTAL_FLIGHT = "TOTAL_FLIGHT";
