export const FETCH_ALL_BOOK_TICKET = "FETCH_ALL_BOOK_TICKET";
export const CREATE_BOOK_TICKET = "CREATE_BOOK_TICKET";
export const DELETE_BOOK_TICKET = "DELETE_BOOK_TICKET";
export const UPDATE_BOOK_TICKET = "UPDATE_BOOK_TICKET";
export const SEARCH_BOOK_TICKET = "SEARCH_BOOK_TICKET";
