export const TOTAL_FLIGHT_BY_PLACE_DEPARTURE =
  "TOTAL_FLIGHT_BY_PLACE_DEPARTURE";
export const TOTAL_FLIGHT_BY_PLACE_DESTINATION =
  "TOTAL_FLIGHT_BY_PLACE_DESTINATION";
export const TOTAL_FLIGHT_BY_TYPE = "TOTAL_FLIGHT_BY_TYPE";
export const TOTAL_FLIGHT_BY_AIRPORT = "TOTAL_FLIGHT_BY_AIRPORT";
