export const FETCH_ALL_FLIGHT_TIME = "FETCH_ALL_FLIGHT_TIME";
export const CREATE_FLIGHT_TIME = "CREATE_FLIGHT_TIME";
export const DELETE_FLIGHT_TIME = "DELETE_FLIGHT_TIME";
export const UPDATE_FLIGHT_TIME = "UPDATE_FLIGHT_TIME";
export const SEARCH_FLIGHT_TIME = "SEARCH_FLIGHT_TIME";
