export const FETCH_ALL_ACCOUNT = "FETCH_ALL_ACCOUNT";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const SEARCH_ACCOUNT = "SEARCH_ACCOUNT";
